# Generated by Django 4.1.1 on 2022-09-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200401_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default='images/users/R.jpg', upload_to='images/users'),
        ),
    ]
